# Generated by Django 4.0 on 2023-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('short_description', models.TextField(verbose_name='краткое описание ')),
                ('long_description', models.TextField(verbose_name='полное описание')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'PLACE',
                'verbose_name_plural': 'PLACES',
            },
        ),
    ]
