# Generated by Django 4.0 on 2023-07-10 17:42

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_number', 'place'], 'verbose_name': 'IMAGE', 'verbose_name_plural': 'IMAGES'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='places',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='полное описание'),
        ),
    ]
