# Generated by Django 3.2.11 on 2023-07-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('id', 'place', 'image')},
        ),
    ]
