# Generated by Django 4.0 on 2023-07-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID места'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='places',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='places',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
    ]
