# Generated by Django 3.2.11 on 2023-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230718_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
