# Generated by Django 4.0 on 2023-07-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_places_place_id_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
