# Generated by Django 3.2.11 on 2023-07-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_places_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number', 'place'], 'verbose_name': 'ИЗОБРАЖЕНИЕ', 'verbose_name_plural': 'ИЗОБРАЖЕНИЕ'},
        ),
    ]
